# ===============================
# POSTGRESQL DB (LOCAL MAC CONNECTING TO DOCKER)
# ===============================
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/jobportal
spring.datasource.username=postgres
spring.datasource.password=PostgresPassword123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# SQL INIT
# ===============================
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

# ===============================
# HIBERNATE
# ===============================
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# ===============================
# REDIS / SESSION (LOCAL MAC CONNECTING TO DOCKER)
# ===============================
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.session.store-type=redis

# ===============================
# QDRANT INIT
# ===============================
qdrant.url=http://localhost:6333

# ===============================
# EMBEDDING SERVICE SWITCH
# ===============================
embedding.mock.enabled=true