# ===============================
# ORACLE DB (LOCAL MAC CONNECTING TO DOCKER)
# ===============================
server.port=9090
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=SYSTEM
spring.datasource.password=OraclePassword123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ===============================
# SQL INIT
# ===============================
spring.sql.init.mode=never

# ===============================
# HIBERNATE
# ===============================
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# ===============================
# REDIS / SESSION (LOCAL MAC CONNECTING TO DOCKER)
# ===============================
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.session.store-type=redis
