-- ============================================================================
-- Job Application Portal — Database Schema (PostgreSQL)
-- ============================================================================

-- 1. Users Table
CREATE TABLE IF NOT EXISTS USERS (
    USER_ID BIGINT PRIMARY KEY,
    EMAIL VARCHAR(200) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    ROLE VARCHAR(30) NOT NULL,
    IS_ACTIVE SMALLINT DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 2. Employer Profiles
CREATE TABLE IF NOT EXISTS EMPLOYER_PROFILES (
    USER_ID BIGINT PRIMARY KEY,
    COMPANY_NAME VARCHAR(200),
    INDUSTRY VARCHAR(100),
    WEBSITE VARCHAR(500),
    DESCRIPTION VARCHAR(2000),
    LOCATION VARCHAR(200),
    CONSTRAINT FK_EMP_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

-- 3. Student Profiles
CREATE TABLE IF NOT EXISTS STUDENT_PROFILES (
    USER_ID BIGINT PRIMARY KEY,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    UNIVERSITY VARCHAR(200),
    MAJOR VARCHAR(100),
    GRADUATION_YEAR SMALLINT,
    PHONE VARCHAR(20),
    SKILLS VARCHAR(2000),
    EXPERIENCE VARCHAR(4000),
    PROJECTS VARCHAR(4000),
    CERTIFICATIONS VARCHAR(2000),
    RESUME_FILE_NAME VARCHAR(255),
    RESUME_CONTENT_TYPE VARCHAR(100),
    CONSTRAINT FK_STU_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

-- 4. Jobs Table
CREATE TABLE IF NOT EXISTS JOBS (
    JOB_ID BIGINT PRIMARY KEY,
    EMPLOYER_USER_ID BIGINT NOT NULL,
    TITLE VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(4000),
    LOCATION VARCHAR(200),
    SALARY_RANGE VARCHAR(100),
    REQUIRED_SKILLS VARCHAR(1000),
    DURATION VARCHAR(100),
    BENEFITS VARCHAR(1000),
    JOB_TYPE VARCHAR(50),
    DEADLINE TIMESTAMP,
    IS_ACTIVE SMALLINT DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_JOB_EMP FOREIGN KEY (EMPLOYER_USER_ID) REFERENCES USERS(USER_ID)
);

-- 5. Applications Table
CREATE TABLE IF NOT EXISTS APPLICATIONS (
    APPLICATION_ID BIGINT PRIMARY KEY,
    STUDENT_USER_ID BIGINT NOT NULL,
    JOB_ID BIGINT NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    APPLIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    RESUME_URL_AT_APPLY VARCHAR(500),
    EMPLOYER_NOTES VARCHAR(2000),
    CONSTRAINT FK_APP_STU FOREIGN KEY (STUDENT_USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_APP_JOB FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID),
    CONSTRAINT UK_APP_STUDENT_JOB UNIQUE (STUDENT_USER_ID, JOB_ID)
);