-- ============================================================================
-- Job Application Portal — Database Schema (Oracle SQL)
-- ============================================================================

-- Drop existing tables and sequences (uncomment for clean reset)
-- DROP TABLE APPLICATIONS;
-- DROP TABLE JOBS;
-- DROP TABLE STUDENT_PROFILES;
-- DROP TABLE EMPLOYER_PROFILES;
-- DROP TABLE USERS;
-- DROP SEQUENCE USERS_SEQ;
-- DROP SEQUENCE JOBS_SEQ;
-- DROP SEQUENCE APPLICATIONS_SEQ;

-- 1. Sequences
CREATE SEQUENCE USERS_SEQ START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE JOBS_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE APPLICATIONS_SEQ START WITH 5000 INCREMENT BY 1 NOCACHE;

-- 2. Users Table
CREATE TABLE USERS (
    USER_ID NUMBER(19,0) PRIMARY KEY,
    EMAIL VARCHAR2(200) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    ROLE VARCHAR2(30) NOT NULL,
    IS_ACTIVE NUMBER(1,0) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 3. Employer Profiles
CREATE TABLE EMPLOYER_PROFILES (
    USER_ID NUMBER(19,0) PRIMARY KEY,
    COMPANY_NAME VARCHAR2(200),
    INDUSTRY VARCHAR2(100),
    WEBSITE VARCHAR2(500),
    DESCRIPTION VARCHAR2(2000),
    LOCATION VARCHAR2(200),
    CONSTRAINT FK_EMP_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

-- 4. Student Profiles
CREATE TABLE STUDENT_PROFILES (
    USER_ID NUMBER(19,0) PRIMARY KEY,
    FIRST_NAME VARCHAR2(100),
    LAST_NAME VARCHAR2(100),
    UNIVERSITY VARCHAR2(200),
    MAJOR VARCHAR2(100),
    GRADUATION_YEAR NUMBER(4,0),
    PHONE VARCHAR2(20),
    SKILLS VARCHAR2(2000),
    EXPERIENCE VARCHAR2(4000),
    PROJECTS VARCHAR2(4000),
    CERTIFICATIONS VARCHAR2(2000),
    RESUME_FILE_NAME VARCHAR2(255),
    RESUME_CONTENT_TYPE VARCHAR2(100),
    CONSTRAINT FK_STU_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

-- 5. Jobs Table
CREATE TABLE JOBS (
    JOB_ID NUMBER(19,0) PRIMARY KEY,
    EMPLOYER_USER_ID NUMBER(19,0) NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    DESCRIPTION VARCHAR2(4000),
    LOCATION VARCHAR2(200),
    SALARY_RANGE VARCHAR2(100),
    REQUIRED_SKILLS VARCHAR2(1000),
    DURATION VARCHAR2(100),
    BENEFITS VARCHAR2(1000),
    JOB_TYPE VARCHAR2(50),
    DEADLINE TIMESTAMP,
    IS_ACTIVE NUMBER(1,0) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_JOB_EMP FOREIGN KEY (EMPLOYER_USER_ID) REFERENCES USERS(USER_ID)
);

-- 6. Applications Table
CREATE TABLE APPLICATIONS (
    APPLICATION_ID NUMBER(19,0) PRIMARY KEY,
    STUDENT_USER_ID NUMBER(19,0) NOT NULL,
    JOB_ID NUMBER(19,0) NOT NULL,
    STATUS VARCHAR2(30) NOT NULL,
    APPLIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    RESUME_URL_AT_APPLY VARCHAR2(500),
    EMPLOYER_NOTES VARCHAR2(2000),
    CONSTRAINT FK_APP_STU FOREIGN KEY (STUDENT_USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_APP_JOB FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID),
    CONSTRAINT UK_APP_STUDENT_JOB UNIQUE (STUDENT_USER_ID, JOB_ID)
);
