-- ============================================================================
-- seed_jobs_data.sql
--
-- Seeds 15 real job postings + their employer accounts + employer profiles.
--
-- DESIGNED TO RUN ON EVERY PIPELINE DEPLOYMENT, not just once. Every insert
-- uses ON CONFLICT DO NOTHING, so running this 1 time or 100 times produces
-- the exact same end state — no duplicate-key errors, no duplicated rows.
--
-- IMPORTANT NOTES:
-- 1. This assumes schema.sql has already been run (tables exist).
-- 2. This deliberately EXCLUDES user IDs 11, 12, 13 (admin@portal.com,
--    student@portal.com, employer@portal.com) because those are already
--    seeded automatically by JobApplicationPortalApplication's
--    CommandLineRunner on every app startup. Do NOT add them here, or you
--    risk a duplicate-key conflict with the CommandLineRunner's own inserts.
-- 3. This also excludes job IDs 100, 201, 217 and their associated users/jobs
--    (test/placeholder data, not part of the real 15 JD set).
-- 4. All 15 employer accounts share a placeholder password hash and are NOT
--    intended to be logged into directly — they exist only so the JOBS
--    table's foreign key (EMPLOYER_USER_ID) has a valid row to point to.
-- 5. IDEMPOTENT BY DESIGN — every INSERT below uses ON CONFLICT DO NOTHING,
--    so this script is safe to run on EVERY pipeline deployment, not just
--    the first one. First run: inserts everything. Every run after that:
--    finds all 44 rows already exist (by primary key) and silently skips
--    them, leaving your data untouched. No errors, no duplicates, no
--    accidental resets of data students/employers may have since added.
-- ============================================================================

BEGIN;

-- ----------------------------------------------------------------------------
-- Employer USERS (15 accounts, one per company, IDs 49-63)
-- ----------------------------------------------------------------------------
INSERT INTO public.users (user_id, email, password_hash, role, is_active, created_at) OVERRIDING SYSTEM VALUE VALUES (49, 'recruiter@carepredict.com', '$2a$10$7EqJtq98hPqEX7fNZaFWoOe6d6.WZRlLqvhZq1Q1QWQlQWQlQWQlQ', 'EMPLOYER', true, '2026-04-08 04:47:41.26978') ON CONFLICT (user_id) DO NOTHING;
INSERT INTO public.users (user_id, email, password_hash, role, is_active, created_at) OVERRIDING SYSTEM VALUE VALUES (50, 'recruiter@oncosysai.com', '$2a$10$7EqJtq98hPqEX7fNZaFWoOe6d6.WZRlLqvhZq1Q1QWQlQWQlQWQlQ', 'EMPLOYER', true, '2026-04-08 04:47:41.26978') ON CONFLICT (user_id) DO NOTHING;
INSERT INTO public.users (user_id, email, password_hash, role, is_active, created_at) OVERRIDING SYSTEM VALUE VALUES (51, 'recruiter@verkada.com', '$2a$10$7EqJtq98hPqEX7fNZaFWoOe6d6.WZRlLqvhZq1Q1QWQlQWQlQWQlQ', 'EMPLOYER', true, '2026-04-08 04:47:41.26978') ON CONFLICT (user_id) DO NOTHING;
INSERT INTO public.users (user_id, email, password_hash, role, is_active, created_at) OVERRIDING SYSTEM VALUE VALUES (52, 'recruiter@northeastern-eai.edu', '$2a$10$7EqJtq98hPqEX7fNZaFWoOe6d6.WZRlLqvhZq1Q1QWQlQWQlQWQlQ', 'EMPLOYER', true, '2026-04-08 04:47:41.26978') ON CONFLICT (user_id) DO NOTHING;
INSERT INTO public.users (user_id, email, password_hash, role, is_active, created_at) OVERRIDING SYSTEM VALUE VALUES (53, 'recruiter@ruegiltgroupe.com', '$2a$10$7EqJtq98hPqEX7fNZaFWoOe6d6.WZRlLqvhZq1Q1QWQlQWQlQWQlQ', 'EMPLOYER', true, '2026-04-08 04:47:41.26978') ON CONFLICT (user_id) DO NOTHING;
INSERT INTO public.users (user_id, email, password_hash, role, is_active, created_at) OVERRIDING SYSTEM VALUE VALUES (54, 'recruiter@meshy.ai', '$2a$10$7EqJtq98hPqEX7fNZaFWoOe6d6.WZRlLqvhZq1Q1QWQlQWQlQWQlQ', 'EMPLOYER', true, '2026-04-08 04:47:41.26978') ON CONFLICT (user_id) DO NOTHING;
INSERT INTO public.users (user_id, email, password_hash, role, is_active, created_at) OVERRIDING SYSTEM VALUE VALUES (55, 'recruiter@aholddelhaize.com', '$2a$10$7EqJtq98hPqEX7fNZaFWoOe6d6.WZRlLqvhZq1Q1QWQlQWQlQWQlQ', 'EMPLOYER', true, '2026-04-08 04:47:41.26978') ON CONFLICT (user_id) DO NOTHING;
INSERT INTO public.users (user_id, email, password_hash, role, is_active, created_at) OVERRIDING SYSTEM VALUE VALUES (56, 'recruiter@fluidai.com', '$2a$10$7EqJtq98hPqEX7fNZaFWoOe6d6.WZRlLqvhZq1Q1QWQlQWQlQWQlQ', 'EMPLOYER', true, '2026-04-08 04:47:41.26978') ON CONFLICT (user_id) DO NOTHING;
INSERT INTO public.users (user_id, email, password_hash, role, is_active, created_at) OVERRIDING SYSTEM VALUE VALUES (57, 'recruiter@truveta.com', '$2a$10$7EqJtq98hPqEX7fNZaFWoOe6d6.WZRlLqvhZq1Q1QWQlQWQlQWQlQ', 'EMPLOYER', true, '2026-04-08 04:47:41.26978') ON CONFLICT (user_id) DO NOTHING;
INSERT INTO public.users (user_id, email, password_hash, role, is_active, created_at) OVERRIDING SYSTEM VALUE VALUES (58, 'recruiter@activesite.org', '$2a$10$7EqJtq98hPqEX7fNZaFWoOe6d6.WZRlLqvhZq1Q1QWQlQWQlQWQlQ', 'EMPLOYER', true, '2026-04-08 04:47:41.26978') ON CONFLICT (user_id) DO NOTHING;
INSERT INTO public.users (user_id, email, password_hash, role, is_active, created_at) OVERRIDING SYSTEM VALUE VALUES (59, 'recruiter@foxxlifesciences.com', '$2a$10$7EqJtq98hPqEX7fNZaFWoOe6d6.WZRlLqvhZq1Q1QWQlQWQlQWQlQ', 'EMPLOYER', true, '2026-04-08 04:47:41.26978') ON CONFLICT (user_id) DO NOTHING;
INSERT INTO public.users (user_id, email, password_hash, role, is_active, created_at) OVERRIDING SYSTEM VALUE VALUES (60, 'recruiter@pyramidglobal.com', '$2a$10$7EqJtq98hPqEX7fNZaFWoOe6d6.WZRlLqvhZq1Q1QWQlQWQlQWQlQ', 'EMPLOYER', true, '2026-04-08 04:47:41.26978') ON CONFLICT (user_id) DO NOTHING;
INSERT INTO public.users (user_id, email, password_hash, role, is_active, created_at) OVERRIDING SYSTEM VALUE VALUES (61, 'recruiter@hms.harvard.edu', '$2a$10$7EqJtq98hPqEX7fNZaFWoOe6d6.WZRlLqvhZq1Q1QWQlQWQlQWQlQ', 'EMPLOYER', true, '2026-04-08 04:47:41.26978') ON CONFLICT (user_id) DO NOTHING;
INSERT INTO public.users (user_id, email, password_hash, role, is_active, created_at) OVERRIDING SYSTEM VALUE VALUES (62, 'recruiter@capital-placement.com', '$2a$10$7EqJtq98hPqEX7fNZaFWoOe6d6.WZRlLqvhZq1Q1QWQlQWQlQWQlQ', 'EMPLOYER', true, '2026-04-08 04:47:41.26978') ON CONFLICT (user_id) DO NOTHING;
INSERT INTO public.users (user_id, email, password_hash, role, is_active, created_at) OVERRIDING SYSTEM VALUE VALUES (63, 'recruiter@rootsinterns.com', '$2a$10$7EqJtq98hPqEX7fNZaFWoOe6d6.WZRlLqvhZq1Q1QWQlQWQlQWQlQ', 'EMPLOYER', true, '2026-04-08 04:47:41.26978') ON CONFLICT (user_id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- EMPLOYER_PROFILES (company info for each of the 15 employer accounts above)
-- ----------------------------------------------------------------------------
INSERT INTO public.employer_profiles (user_id, company_name, industry, website, description, location) VALUES (49, 'CarePredict', 'Healthcare Technology', 'https://carepredict.com', 'CarePredict blends compassion with data science to predict early health declines in seniors and empower caregivers to act sooner. 22+ patents, two CES Innovation Awards.', 'Plantation, FL') ON CONFLICT (user_id) DO NOTHING;
INSERT INTO public.employer_profiles (user_id, company_name, industry, website, description, location) VALUES (50, 'OncoSys AI', 'Health AI / Oncology', 'https://oncosysai.com', 'OncoSys AI builds oncology data validation pipelines and scoring systems to support biopharma pilots with real-world clinical data.', 'Cambridge, MA') ON CONFLICT (user_id) DO NOTHING;
INSERT INTO public.employer_profiles (user_id, company_name, industry, website, description, location) VALUES (51, 'Verkada', 'Physical Security AI', 'https://verkada.com', 'Verkada transforms how organizations protect people and places with an AI-powered platform. 31,000+ customers, $5.8B valuation, 2M+ devices in 170 countries.', 'San Mateo, CA') ON CONFLICT (user_id) DO NOTHING;
INSERT INTO public.employer_profiles (user_id, company_name, industry, website, description, location) VALUES (52, 'Institute for Experiential AI (EAI) at Northeastern University', 'AI Research', 'https://ai.northeastern.edu', 'The EAI at Northeastern partners with industry to translate AI research into real-world solutions across healthcare, sustainability, and enterprise domains.', 'Portland, ME') ON CONFLICT (user_id) DO NOTHING;
INSERT INTO public.employer_profiles (user_id, company_name, industry, website, description, location) VALUES (53, 'Rue Gilt Groupe', 'E-Commerce / Fashion Tech', 'https://ruegiltgroupe.com', 'Rue Gilt Groupe operates Rue La La, Gilt, and ShopSimon, connecting 50M+ members with luxury brands at up to 70% off using cutting-edge AI and ML.', 'Boston, MA') ON CONFLICT (user_id) DO NOTHING;
INSERT INTO public.employer_profiles (user_id, company_name, industry, website, description, location) VALUES (54, 'Meshy LLC', 'AI / 3D Technology', 'https://meshy.ai', 'Meshy builds AI-powered 3D generation tools for creators and developers, leveraging ML for recommendation, segmentation, and growth analytics.', 'Sunnyvale, CA') ON CONFLICT (user_id) DO NOTHING;
INSERT INTO public.employer_profiles (user_id, company_name, industry, website, description, location) VALUES (55, 'Ahold Delhaize USA', 'Retail / Grocery', 'https://aholddelhaize.com', 'One of the largest food retail groups in the world, operating Stop & Shop, Food Lion, Giant, and more with strong focus on data-driven operations.', 'Quincy, MA') ON CONFLICT (user_id) DO NOTHING;
INSERT INTO public.employer_profiles (user_id, company_name, industry, website, description, location) VALUES (56, 'FluidAI Medical', 'Medical AI / MedTech', 'https://fluid.ai', 'FluidAI develops data-driven surgical solutions combining proprietary sensors, EHR data, and AI to enable earlier identification of clinical deterioration.', 'Kitchener, ON, Canada') ON CONFLICT (user_id) DO NOTHING;
INSERT INTO public.employer_profiles (user_id, company_name, industry, website, description, location) VALUES (57, 'Truveta', 'Health Data Platform', 'https://truveta.com', 'Truveta is the world''s first health provider-led data platform enabling researchers to find cures faster and transforming medicine with unprecedented data.', 'Seattle, WA') ON CONFLICT (user_id) DO NOTHING;
INSERT INTO public.employer_profiles (user_id, company_name, industry, website, description, location) VALUES (58, 'Active Site', 'AI x Biology Research', 'https://activesite.org', 'Active Site is a research nonprofit studying the intersection of AI and biology, measuring how AI augments human performance in biological experimentation.', 'Cambridge, MA') ON CONFLICT (user_id) DO NOTHING;
INSERT INTO public.employer_profiles (user_id, company_name, industry, website, description, location) VALUES (59, 'Foxx Life Sciences', 'Scientific Manufacturing', 'https://foxxlifesciences.com', 'Foxx Life Sciences delivers industry-leading laboratory solutions and filtration products with a focus on 100% customer satisfaction and scientific innovation.', 'Londonderry, NH') ON CONFLICT (user_id) DO NOTHING;
INSERT INTO public.employer_profiles (user_id, company_name, industry, website, description, location) VALUES (60, 'Pyramid Global Hospitality', 'Hospitality', 'https://pyramidglobalhosp.com', 'Pyramid Global Hospitality is a leading hotel management company operating world-class resort and hotel properties across the US and globally.', 'Waltham, MA') ON CONFLICT (user_id) DO NOTHING;
INSERT INTO public.employer_profiles (user_id, company_name, industry, website, description, location) VALUES (61, 'Harvard Medical School (Church Lab)', 'Biotech Research', 'https://arep.med.harvard.edu', 'The Church Lab at Harvard Medical School pioneers genome sequencing, DNA assembly, genome editing, and machine learning for protein engineering.', 'Boston, MA') ON CONFLICT (user_id) DO NOTHING;
INSERT INTO public.employer_profiles (user_id, company_name, industry, website, description, location) VALUES (62, 'Capital Placement', 'Internship Agency', 'https://capital-placement.com', 'Capital Placement is the largest and highest rated international internship provider globally, working with 4,000+ employers and leading universities worldwide.', 'London, UK / New York, NY / Singapore / Remote') ON CONFLICT (user_id) DO NOTHING;
INSERT INTO public.employer_profiles (user_id, company_name, industry, website, description, location) VALUES (63, 'Roots Interns', 'NGO / Education', 'https://rootsinterns.com', 'Roots Interns places students in meaningful international internship experiences at nonprofits and social impact organizations worldwide.', 'Siem Reap, Cambodia') ON CONFLICT (user_id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- JOBS (the 15 real job descriptions, IDs 202-216)
-- ----------------------------------------------------------------------------
INSERT INTO public.jobs (job_id, employer_user_id, title, description, location, salary_range, required_skills, duration, benefits, company_name, job_type, deadline, is_active, created_at) OVERRIDING SYSTEM VALUE VALUES (202, 49, 'Back End Software Engineer Co-Op', 'As a Backend Software Engineer Intern at CarePredict, you will design and build Java Spring Boot microservices and RESTful APIs powering real-time senior care monitoring. You will integrate WebSocket-based real-time communication for live caregiver alerts, model relational schemas and write efficient SQL queries, and implement distributed messaging using Apache Kafka for event-driven data pipelines. You will participate in Agile ceremonies including stand-ups, sprint planning, and retrospectives. You will assist with deploying services using AWS (ECS, RDS, CloudWatch) and support CI/CD pipeline improvements and system observability. Every feature you build will help caregivers support seniors more proactively — your work will run in production in real senior-care environments. CarePredict has 22+ issued patents, two CES Innovation Awards, and the Argentum Best of the Best Award (2021). The role is based onsite in Plantation, FL with a relocation bonus of $1,000–$15,000 available for non-residents of South Florida.', 'Plantation, FL (On-site)', '$35/hr', 'Java, Spring Boot, REST APIs, Kafka, WebSockets, SQL, AWS, Git, OOP', '4 months', 'Relocation bonus $1,000-$15,000, mentorship from senior engineers', 'CarePredict', 'CO_OP', '2026-07-10 00:00:00', true, '2026-06-17 04:47:41.26978') ON CONFLICT (job_id) DO NOTHING;
INSERT INTO public.jobs (job_id, employer_user_id, title, description, location, salary_range, required_skills, duration, benefits, company_name, job_type, deadline, is_active, created_at) OVERRIDING SYSTEM VALUE VALUES (203, 50, 'Data Engineering / ML Co-op', 'As a Data Engineering / ML Co-op at OncoSys AI, you will work directly with the founder on the oncology data validation pipeline ahead of the company''s first biopharma pilot in Q3. Responsibilities include writing and optimizing SQL queries for cohort analysis using BigQuery and Snowflake, performing FHIR/HL7 data mapping from clinical sources including Epic and TCGA, building ETL workflows for real-world oncology data, supporting trust packet generation pipeline testing, and documenting data quality findings. Strong Python and SQL skills are required. Exposure to clinical data formats (FHIR/HL7) is a plus. The role is 100% remote with a July 13, 2026 start date and runs through December 19, 2026 at 32–40 hours per week. This is an unpaid position at a startup in the funding stage, but is academic credit eligible. A July start is ideal given the Q3 pilot timeline, though September works too.', 'Cambridge, MA (Remote)', 'Unpaid (academic credit eligible)', 'Python, SQL, BigQuery, Snowflake, FHIR, HL7, ETL, Data Engineering', '6 months (Jul 13 - Dec 19, 2026)', 'Academic credit eligible, 100% remote, direct founder mentorship', 'OncoSys AI', 'CO_OP', '2026-07-12 00:00:00', true, '2026-06-19 04:47:41.26978') ON CONFLICT (job_id) DO NOTHING;
INSERT INTO public.jobs (job_id, employer_user_id, title, description, location, salary_range, required_skills, duration, benefits, company_name, job_type, deadline, is_active, created_at) OVERRIDING SYSTEM VALUE VALUES (204, 51, 'AI Software Engineering Intern', 'At Verkada, you will build the next generation of intelligent protection systems that secure people and physical spaces using AI. This role focuses on developing advanced intrusion alarms, perimeter monitoring, and personal safety solutions powered by multimodal data — combining signals from sensors, audio, and video. You will operate in a highly iterative environment, rapidly turning ideas into prototypes and scaling them into production systems. A key part of the role is exploring and applying cutting-edge large video and audio models to solve real-world security challenges. Specific responsibilities include designing and building AI-powered intrusion detection and alarm systems, developing intelligent perimeter monitoring and real-time threat detection capabilities, working with multimodal data (video, audio, and sensor inputs) to create robust safety systems, rapidly prototyping and iterating on new ideas from concept to deployment, exploring and integrating large-scale video and audio models for perception and anomaly detection, and optimizing systems for real-time performance across edge and cloud environments. Verkada has more than 31,000 customers including 100+ of the Fortune 500, a $5.8B valuation, more than $1 billion in annualized revenue, and more than 2 million devices deployed across 170+ countries. Internship dates: August 31 – December 18, 2026. On-site at HQ in San Mateo, CA. Visa sponsorship available.', 'San Mateo, CA (On-site)', '$55 - $65/hr', 'Machine Learning, Multimodal AI, Python, Video/Audio Models, APIs, Docker, Distributed Systems', '4 months (Aug 31 - Dec 18, 2026)', 'Monthly housing stipend, daily catered lunch, intern events, visa sponsorship available', 'Verkada', 'INTERNSHIP', '2026-08-01 00:00:00', true, '2026-06-22 04:47:41.26978') ON CONFLICT (job_id) DO NOTHING;
INSERT INTO public.jobs (job_id, employer_user_id, title, description, location, salary_range, required_skills, duration, benefits, company_name, job_type, deadline, is_active, created_at) OVERRIDING SYSTEM VALUE VALUES (205, 52, 'Data Scientist Co-op', 'The Data Scientist Co-op at the Institute for Experiential AI (EAI) at Northeastern University will work under the supervision of the Director at AISH and collaborate with Data Scientists and Data Engineers within the organization. Key responsibilities include conducting exploratory data analysis (EDA) on diverse datasets including structured, unstructured, and time-series data; developing, training, and optimizing machine learning pipelines for supervised, unsupervised, and semi-supervised learning tasks; designing computer vision solutions covering object detection, segmentation, action recognition, and image classification using modern ML architectures; building and implementing generative AI models for text and multimodal data leveraging large language models (LLMs) and fine-tuning and in-context learning techniques; collaborating with Data Scientists and Data Engineers on multi-functional projects contributing to end-to-end development, deployment, and optimization of AI solutions; and participating actively in Agile development practices including sprint planning, retrospectives, and project management. Required skills include advanced proficiency in Python and its ecosystem (Pandas, NumPy, Scikit-Learn, Matplotlib, Seaborn), demonstrated experience with deep learning frameworks (TensorFlow, PyTorch), strong understanding of computer vision with practical OpenCV experience, expertise in NLP with transformer-based models (GPT, BERT), and practical SQL knowledge. Preferred: cloud deployment experience (AWS, Azure, GCP), Docker/Kubernetes, CI/CD, and MLOps. Expected start date: July 2026. On-site at the Roux Institute in Portland, ME.', 'Portland, ME (On-site)', '$35 - $40/hr', 'Python, TensorFlow, PyTorch, Pandas, NumPy, Scikit-learn, SQL, OpenCV, NLP, Transformers, Docker', '6 months', 'Mentorship from AI researchers, Agile team, research publication opportunities', 'Institute for Experiential AI (EAI) at Northeastern University', 'CO_OP', '2026-07-31 00:00:00', true, '2026-06-12 04:47:41.26978') ON CONFLICT (job_id) DO NOTHING;
INSERT INTO public.jobs (job_id, employer_user_id, title, description, location, salary_range, required_skills, duration, benefits, company_name, job_type, deadline, is_active, created_at) OVERRIDING SYSTEM VALUE VALUES (206, 53, 'AI Scientist Co-Op', 'Rue Gilt Groupe is looking for an AI Scientist Co-op to join its industry-leading AI & ML Team. In this role, you will partner with expert scientists and engineers to architect innovative fashion-tech solutions fueling the profitable, off-price luxury business across Rue La La, Gilt, and ShopSimon, inspiring confidence and sparking delight in over 50M customers. Responsibilities include developing high-impact AI solutions — including Transformer-based recommenders, GenAI chatbots, Computer Vision, and advanced predictive models — to drive revenue and hyper-personalize the shopping experience; partnering with stakeholders across Marketing, Merchandising, and Executive Leadership to transform business challenges into technical roadmaps blending classic ML with state-of-the-art frameworks; engineering robust real-time and batch data pipelines capable of handling massive scale in the cloud; leveraging a modern tech stack (Spark, TensorFlow, PyTorch, Snowflake, Airflow, AWS) to empower decision-making for internal operations and customer-facing products; deploying scalable cloud-native AI architectures with rigorous monitoring and optimization; championing a Responsible AI framework ensuring all GenAI and ML applications adhere to strict ethical standards and data safety protocols; and driving continuous experimentation and rapid iteration within cross-functional Agile teams. Required: Master''s in Computer Science, Data Science, or Engineering; expertise in Deep Learning (TensorFlow, PyTorch); production-grade Python and SQL; strong CS fundamentals including system design and algorithms; and experience driving the full ML lifecycle from feature engineering to deployment.', 'Boston, MA (On-site)', '$40/hr', 'Python, TensorFlow, PyTorch, Spark, SQL, AWS, Airflow, Snowflake, Deep Learning, GenAI, LLMs', '6 months', 'Mentorship from senior scientists, end-to-end ML ownership, modern tech stack', 'Rue Gilt Groupe', 'CO_OP', '2026-07-31 00:00:00', true, '2026-06-15 04:47:41.26978') ON CONFLICT (job_id) DO NOTHING;
INSERT INTO public.jobs (job_id, employer_user_id, title, description, location, salary_range, required_skills, duration, benefits, company_name, job_type, deadline, is_active, created_at) OVERRIDING SYSTEM VALUE VALUES (207, 54, 'Data Science Intern', 'Meshy LLC is looking for a high-caliber Data Science Intern to join its U.S. team. This is a hands-on, applied role where you will work directly on business-critical machine learning and analytics initiatives alongside senior data science leadership. You will contribute to high-impact projects such as recommendation systems, user segmentation, and churn analysis. This is not a research-only internship — you will solve real product and growth problems with measurable business outcomes, directly influencing product strategy and monetization decisions. Key responsibilities include supporting the development and validation of machine learning models including recommendation systems, user segmentation, and churn prediction; assisting in building LTV and revenue forecasting models to support growth and monetization strategy; designing and analyzing experiments to evaluate model effectiveness and business impact; conducting exploratory data analysis across both structured (schema-ready) and raw datasets; building dashboards and clear data narratives to communicate findings effectively; and collaborating with Product, Growth, and Engineering teams to translate insights into actionable strategies. Duration is 3–6 months, full-time during summer and part-time during academic term. Locations: Sunnyvale, CA or Seattle, WA (Hybrid).', 'Sunnyvale, CA / Seattle, WA (Hybrid)', '$18 - $25/hr', 'Python, Pandas, NumPy, Scikit-learn, SQL, Machine Learning, Statistics, AI', '3-6 months', 'Flexible duration, part-time option during academic term', 'Meshy LLC', 'INTERNSHIP', '2026-07-31 00:00:00', true, '2026-06-27 04:47:41.26978') ON CONFLICT (job_id) DO NOTHING;
INSERT INTO public.jobs (job_id, employer_user_id, title, description, location, salary_range, required_skills, duration, benefits, company_name, job_type, deadline, is_active, created_at) OVERRIDING SYSTEM VALUE VALUES (208, 55, 'Data Analytics Co-op - Fall 2026', 'The Data Analytics Co-op at Ahold Delhaize USA sits within the Consumer Decision & Sciences (C&DS) department, a data-driven team with a wide range of technical skills and responsibilities. Some teams focus on analyzing data trends and providing insights; others are tasked with building and maintaining the data products that support these analyses. This role will work collaboratively with digital product managers, fulfillment data visualization analysts, data scientists, IT, technical teams, and fulfillment teams to develop analytical solutions enabling reporting end users to understand and improve fulfillment performance. The co-op is expected to develop a deep understanding of the fulfillment business processes and how these processes are captured in data environments, and use this knowledge to consult on data pipelines and develop data models and dashboards to support the fulfillment and brand operations teams. Required: working towards a degree in Data Analytics, Computer Science or related field; coding experience in SQL and/or Python; understanding of relational and non-relational data; knowledge of fact and dimensional modeling. PowerBI or Tableau is a plus. Applicants must be currently enrolled in a bachelor''s or master''s degree program, authorized to work in the United States on a full-time basis, and available from July 13, 2026 through December 4, 2026. Hybrid: minimum three days per week in the Quincy, MA office. Salary range: $20.00–$34.20/hr (IL/MA/MD).', 'Quincy, MA (Hybrid - min 3 days/week)', '$20 - $34.20/hr', 'SQL, Python, PowerBI, Tableau, Data Visualization, Relational Data, Dimensional Modeling', '6 months (Jul 13 - Dec 4, 2026)', 'Hybrid flexibility, cross-functional team exposure, large enterprise data environment', 'Ahold Delhaize USA', 'CO_OP', '2026-07-31 00:00:00', true, '2026-06-07 04:47:41.26978') ON CONFLICT (job_id) DO NOTHING;
INSERT INTO public.jobs (job_id, employer_user_id, title, description, location, salary_range, required_skills, duration, benefits, company_name, job_type, deadline, is_active, created_at) OVERRIDING SYSTEM VALUE VALUES (209, 56, 'Data and AI Engineering Associate (Co-op)', 'FluidAI Medical is specialized in the development and deployment of data-driven surgical solutions with an initial focus on general and gastrointestinal surgery. Technologies integrate medical devices, software, and artificial intelligence into platforms that address real clinical and operational challenges across the continuum of surgical care. The Data and AI Engineering Associate role centers around extracting clinical value from data produced by proprietary sensors and systems to improve patient outcomes. Responsibilities include designing, building, and maintaining data pipelines that ingest, clean, transform, and consolidate data from multiple sources into reliable, structured outputs; translating regulatory requirements (HIPAA, PHIPA) to product specifications and ensuring compliance; developing backend services, APIs, and web interfaces that process data and present results and analytics to end users; assisting in conducting technical risk and privacy impact assessments; and supporting other teams with software and data needs as required. Required skills: demonstrated knowledge of backend architecture design and implications on development, security, and privacy; strong knowledge of data structures, database fundamentals (SQL and relational databases); strong knowledge of back-end development (Python preferred); experience building data pipelines or ETL processes (preferred); good knowledge of website front-end development (HTML, JavaScript, CSS; React/TypeScript a plus); familiarity with data-processing libraries (e.g., Pandas); version control (Git); and Agile software development experience. Optional: Docker, GitLab CI. Note: This position is made possible through wage subsidy grants. Participants must be a Canadian citizen, permanent resident, or person granted refugee status in Canada. International students are not eligible. Position available September 2026 at Kitchener HQ (Medical Innovation Xchange).', 'Kitchener, ON, Canada (On-site)', '$22 - $25/hr', 'Python, SQL, Docker, TypeScript, React, Git, ETL, APIs, Agile, Machine Learning', '4 months (September 2026)', 'Workshops, offsite events, full technical stack exposure', 'FluidAI Medical', 'CO_OP', '2026-07-31 00:00:00', true, '2026-06-09 04:47:41.26978') ON CONFLICT (job_id) DO NOTHING;
INSERT INTO public.jobs (job_id, employer_user_id, title, description, location, salary_range, required_skills, duration, benefits, company_name, job_type, deadline, is_active, created_at) OVERRIDING SYSTEM VALUE VALUES (210, 57, 'Software Engineering Intern', 'Truveta is the world''s first health provider-led data platform with a vision of Saving Lives with Data. Its mission is to enable researchers to find cures faster, empower every clinician to be an expert, and help families make the most informed decisions about their care. The Software Engineering Intern role is designed for students pursuing an undergraduate or graduate degree. Candidates must be a sophomore, junior, or senior in college, enrolled in a graduate program, or have graduated within the past year. As a Truveta intern, you will work alongside technology leaders possessing deep technical experience, helping to build real-world intelligence that is unlocking breakthrough discoveries and transforming medicine with unprecedented data and predictive AI. You will contribute to meaningful and impactful projects, working on real product and growth problems. The internship is a minimum 10-week experience, with opportunities to extend based on company needs and mutual interest. The role is based in the Greater Seattle area with interns asked to come into the office several days per week (Hybrid). Note: Truveta is not accepting interns who need CPT at this time. All applicants must be authorized to work in the United States for any employer — the company is unable to sponsor work visas or permits (F-1 OPT, H1-B).', 'Seattle, WA (Hybrid)', '$20/hr', 'Java, Python, C#, .NET, Computer Science, Software Engineering', '10+ weeks', 'Company-issued laptop and equipment, full-time opportunity consideration', 'Truveta', 'INTERNSHIP', '2026-07-31 00:00:00', true, '2026-06-25 04:47:41.26978') ON CONFLICT (job_id) DO NOTHING;
INSERT INTO public.jobs (job_id, employer_user_id, title, description, location, salary_range, required_skills, duration, benefits, company_name, job_type, deadline, is_active, created_at) OVERRIDING SYSTEM VALUE VALUES (211, 58, 'Molecular Biology Associate Co-op', 'Active Site is a research nonprofit studying the intersection of AI and biology. It collects real-world data to measure how AI augments human performance in biological experimentation, using findings to advance the science of AIxBio. The organization''s work shapes how new technologies like AI interface with biological research. The Molecular Biology Associate Co-op role involves working independently on DNA assembly. Core tasks include working in a BSL-1 lab completing DNA design, assembly, purification, and cloning. As part of the AI component, you will work with AI tools like Claude Code. The work environment is designed for highly autonomous researchers — you will not receive day-to-day technical mentorship or assistance; instead, you will have the unique opportunity to fully own your research strategy, manage your own reagent budget, and independently drive your DNA assembly projects. Requirements: currently enrolled in or holding a bachelor''s degree in Biology, Molecular Biology, Microbiology, Bioengineering, Biochemistry, or a closely related discipline; 3 months of independent, iterative, and project-based research experience in PCR, gel electrophoresis, and molecular cloning; demonstrated understanding of primer design, molecular software (Benchling), and molecular cloning methods. Work authorization: open to U.S. citizens, permanent residents, and individuals currently authorized to work in the U.S. Active Site is an E-Verify employer. Hours: 8:45 AM–5:15 PM, no hybrid/remote. Deadline: August 1, 2026.', 'Cambridge, MA (On-site)', '$30/hr', 'PCR, Gel Electrophoresis, Molecular Cloning, Primer Design, DNA Assembly, Benchling, Claude AI', '6 months', 'Full research autonomy, unique AIxBio experience', 'Active Site', 'CO_OP', '2026-08-01 00:00:00', true, '2026-06-29 04:47:41.26978') ON CONFLICT (job_id) DO NOTHING;
INSERT INTO public.jobs (job_id, employer_user_id, title, description, location, salary_range, required_skills, duration, benefits, company_name, job_type, deadline, is_active, created_at) OVERRIDING SYSTEM VALUE VALUES (212, 59, 'Sales Co-op', 'Foxx Life Sciences is an equal opportunity employer seeking a talented and motivated intern to join the sales team. This sales internship provides a unique opportunity to gain hands-on experience in the scientific manufacturing industry while working with a reputable and established company focused on 100% customer satisfaction and industry-leading solutions. Essential job functions include assisting the sales team in managing customer accounts and orders, ensuring accuracy and timely delivery; collaborating with product specialists to provide technical support and information to customers; conducting market research and analysis to identify potential business opportunities and emerging trends; assisting in the preparation and coordination of marketing campaigns and promotional materials; supporting various administrative tasks such as data entry, documentation, and filing; and contributing to ongoing projects and initiatives as assigned by the supervisor. Requirements: must be currently enrolled as a full-time student; pursuing a degree in a scientific field (e.g., Biology, Chemistry, Physics) or a related discipline; strong interest in the scientific research and laboratory supply industry. All interns will spend the first 30 days of their internship learning about Foxx Life Sciences by working in the Clean Room. Compensation: $15/hr. Location: Londonderry, NH (On-site).', 'Londonderry, NH (On-site)', '$15/hr', 'Market Research, Sales, Data Entry, Scientific Research, Marketing Campaigns', '6 months', 'Hands-on experience in scientific manufacturing, first 30 days Clean Room training', 'Foxx Life Sciences', 'CO_OP', '2026-07-31 00:00:00', true, '2026-06-23 04:47:41.26978') ON CONFLICT (job_id) DO NOTHING;
INSERT INTO public.jobs (job_id, employer_user_id, title, description, location, salary_range, required_skills, duration, benefits, company_name, job_type, deadline, is_active, created_at) OVERRIDING SYSTEM VALUE VALUES (213, 60, 'Hotel Sales and Events Co-op', 'Pyramid Global Hospitality is looking for a highly engaging, customer-focused individual to join the sales team as a Hotel Sales and Events Co-op. The successful candidate will have a proven track record of providing exceptional service, is open to learning and leading by example, responds in a professional and courteous manner to guests and team, and is there to support the team both personally and professionally. The Sales Coordinator will be primarily responsible for supporting the Sales Team and ensuring they have the tools, supplies, and resources needed to deliver service that sets the property apart. They are responsible for creating a positive guest interaction that builds anticipation for upcoming visits. Role responsibilities include: answering incoming phone calls, qualifying inquiries, and setting up calls with the Sales and Catering Sales Manager; sending packages and answering general questions; creating monthly recaps of leads and updates; assisting in creating contracts, estimates, and site tours; creating Sales and Catering kits and restocking the supply area; controlling office supplies and ordering when necessary; updating the Sales System with actuals after completion of events; sending Thank You cards and emails; assisting with creating group resumes; and assisting in the operations of events. Compensation: $24/hr. Location: Waltham, MA (On-site).', 'Waltham, MA (On-site)', '$24/hr', 'Customer Service, Communication, Teamwork, Interpersonal Skills, Multitasking', '6 months', 'Hospitality career growth, world-class property experience', 'Pyramid Global Hospitality', 'CO_OP', '2026-07-31 00:00:00', true, '2026-06-21 04:47:41.26978') ON CONFLICT (job_id) DO NOTHING;
INSERT INTO public.jobs (job_id, employer_user_id, title, description, location, salary_range, required_skills, duration, benefits, company_name, job_type, deadline, is_active, created_at) OVERRIDING SYSTEM VALUE VALUES (214, 61, 'Bio-automation Internship', 'The Church Lab at Harvard Medical School has pioneered development of technologies for genome sequencing, DNA assembly, genome editing, writing, and recoding, and machine learning for protein engineering. The lab is interested in designing new-to-nature biological systems that can have real-world applications and expand our understanding of natural biological systems. An exciting research opportunity is available for students with an engineering background to contribute to a research project developing high-throughput autonomous robotics that accelerate biological research. The applications of this project will allow expansion of the genetic code beyond 20 standard amino acids in order to translate proteins with expanded chemistries. Students will collaborate with life scientists in the lab to bridge engineering and synthetic biology. Skills required: computer programming in Python, and prior research experience in robotics and/or electronic engineering. Experience in biology/biochemistry is a plus. Students will have the opportunity to work with senior scientists in the lab and be trained in computation and lab techniques. Learning outcomes include developing a broad set of research skills, learning advanced techniques, developing experience in novel research directions, and increasing independence in experimental design and data analysis. The student will have opportunities to present data in both individual meetings and group settings. Number of hours and length of experience is negotiable from part-time to full-time. Mentorship from a postdoctoral fellow in the lab and meetings with PI George Church. Note: this internship is only through research for credit or external fellowship. The laboratory will cover all research costs. PI: George Church, PhD.', 'Boston, MA (On-site)', 'Unpaid (research credit / external fellowship)', 'Python, Robotics, Electrical Engineering, Device Prototyping, Biological Research', '4-6 months (negotiable)', 'Mentorship from postdocs and PI George Church, all research costs covered', 'Harvard Medical School (Church Lab)', 'CO_OP', '2026-07-31 00:00:00', true, '2026-06-17 04:47:41.26978') ON CONFLICT (job_id) DO NOTHING;
INSERT INTO public.jobs (job_id, employer_user_id, title, description, location, salary_range, required_skills, duration, benefits, company_name, job_type, deadline, is_active, created_at) OVERRIDING SYSTEM VALUE VALUES (215, 62, '2026 Marketing & Go to Market Co-Op', 'Capital Placement is the largest and highest rated international internship provider globally, working with leading universities and over 4,000 employers worldwide, helping students gain international experience. The 2026 Marketing and Go to Market Co-op is available in London, New York, Singapore, and Remote. Following your application, Capital Placement conducts a structured assessment of your academic profile, career objectives, and program preferences. Eligible students are then matched to a guaranteed co-op placement within their chosen industry through the international employer network. End-to-end support is provided throughout the process, including interview preparation, onboarding, visa guidance, and accommodation assistance where applicable. Responsibilities may include: developing and executing marketing campaigns across digital and traditional channels to drive brand awareness and lead generation; conducting market and competitor research to inform GTM strategy and product positioning; creating and refining content including copy, presentations, and social media assets for target audiences; collaborating with Sales, Product, and Creative teams to align messaging and support pipeline growth; and analysing campaign performance using key metrics and dashboards to optimise spend and strategy. Duration: 4–6 months depending on the program. Flexible start dates — program is open all year round. Full-time: 35–45 hours/week. Part-time: 20–25 hours/week. Paid and unpaid options available. Program fees apply. Locations: London, New York, Singapore, Remote.', 'London / New York / Singapore / Remote', 'Paid and Unpaid options (program fees apply)', 'Marketing, Digital Marketing, Strategic Thinking, Brand Marketing, GTM, Lead Generation', '4-6 months', 'End-to-end placement support, visa guidance, accommodation, career coaching', 'Capital Placement', 'CO_OP', '2026-12-31 00:00:00', true, '2026-06-02 04:47:41.26978') ON CONFLICT (job_id) DO NOTHING;
INSERT INTO public.jobs (job_id, employer_user_id, title, description, location, salary_range, required_skills, duration, benefits, company_name, job_type, deadline, is_active, created_at) OVERRIDING SYSTEM VALUE VALUES (216, 63, 'Communications & Marketing Internship, Cambodia', 'Roots Interns places students in meaningful international internship experiences. This Communications and Marketing Internship is based in Siem Reap, Cambodia, working with REACH Siem Reap, a social impact nonprofit focused on breaking the cycle of poverty and reducing the socio-economic gap through education. REACH Siem Reap provides English classes alongside a range of 12 integrated programs and takes a holistic approach to education initiatives, supporting children from 5 to 18 years old while offering outreach assistance to their families. The intern will help spread word and raise support for these programs. Responsibilities include: supporting the development and execution of overall marketing strategies; managing growth, engagement, and performance across social media platforms; producing content for blogs, newsletters, articles, and other digital channels; contributing to video editing and basic post-production tasks; developing written content that drives organic growth on social media accounts; and analyzing campaign performance and preparing reports with actionable insights. Requirements: academic background or experience in marketing, communications, or related field preferred; fluent English; familiarity with social media platforms; computer literate; meticulous attention to detail; excellent written communication; culturally aware and open-minded; valid police check required for working with children. This is an unpaid voluntary work placement. Placement fees apply: 8 weeks USD 1,777; 12 weeks USD 2,173; 16 weeks USD 2,570; 20 weeks USD 2,967; 26 weeks USD 3,547. Start and end dates are flexible. Location: Siem Reap, Cambodia (On-site).', 'Siem Reap, Cambodia (On-site)', 'Unpaid (placement fee: $1,777 - $3,547)', 'Marketing, Communications, Social Media, Content Creation, Written Communication', '8-26 weeks (flexible)', 'International immersive experience, daily supervisor mentorship', 'Roots Interns', 'CO_OP', '2026-12-31 00:00:00', true, '2026-05-28 04:47:41.26978') ON CONFLICT (job_id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- Bump sequences so future auto-generated IDs (new signups, new job posts)
-- never collide with these hardcoded IDs.
--
-- Uses GREATEST so this is also safe to run on every deploy: if real users
-- have signed up or real jobs have been posted since the last run (pushing
-- the sequence past 63/216 already), this will NOT move it backward and
-- risk a future collision. It only bumps the sequence up if it's currently
-- behind where these seed IDs need it to be.
-- ----------------------------------------------------------------------------
SELECT pg_catalog.setval(
    'public.users_user_id_seq',
    GREATEST(63, (SELECT last_value FROM public.users_user_id_seq)),
    true
);
SELECT pg_catalog.setval(
    'public.jobs_job_id_seq',
    GREATEST(216, (SELECT last_value FROM public.jobs_job_id_seq)),
    true
);

COMMIT;